# Generated by Django 4.0 on 2024-03-11 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlimagen', models.URLField()),
                ('enlace', models.URLField()),
                ('titular', models.CharField(max_length=150)),
                ('autores', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fextraccion', models.DateTimeField()),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfuente', models.CharField(max_length=50)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuente', to='noticias.noticia')),
            ],
        ),
    ]
